require("heinunez.plugins-setup")
require("heinunez.core.options")
require("heinunez.core.keymaps")
require("heinunez.core.colorscheme")
require("heinunez.plugins.comment")
require("heinunez.plugins.lualine")
require("heinunez.plugins.nvim-tree")
require("heinunez.plugins.telescope")
require("heinunez.plugins.lsp-zero")
require("heinunez.plugins.nvim-cmp")
require("heinunez.plugins.autopairs")
require("heinunez.plugins.treesitter")
require("heinunez.plugins.gitsigns")

